# Generated by Django 4.1.2 on 2022-10-29 17:45

from django.db import migrations, models
import fla_yolo.models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_yolo', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=fla_yolo.models.scramble_uploaded_filename, verbose_name='Uploaded Image'),
        ),
    ]
